version: "3"
services:
  ruby-jekyllrb:
    container_name: container-jekyllrb
    env_file:
      - .env
    build:
      context: ./ruby
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "2226:22"
    volumes:
      - ./www:/var/www
      - ${PROJECTS_FOLDER}:/var/www/jekyllrb
    command: ["supervisord", "-n"]